name: nw-plate
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::fastapi
  - conda-forge::uvicorn
  - conda-forge::pydantic
  - conda-forge::libsqlite
  - pip
  - pip:
    - openai
